AuctionsTable: # name, we specify for this resource
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: AuctionsTable # any name for the table 
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S # S stands for string here
        KeySchema: 
          - AttributeName: id 
            KeyType: HASH